import type { Metadata } from 'next'
import { Inter as FontSans } from 'next/font/google'

import '@/styles/globals.css'
import { cn } from '@/lib/utils'
import { fontJakarta, fontMono } from '@/styles/font'

export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
})
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html lang="en">
            <body
                className={cn(
                    'bg-background mx-4 min-h-screen border border-red-400 font-sans antialiased',
                    fontSans.variable,
                    fontJakarta.variable,
                    fontMono.variable
                )}
            >
                {children}
            </body>
        </html>
    )
}
